name: staff_ics
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  cached_network_image: ^3.2.0
  get_storage: ^2.0.3
  auto_size_text: ^3.0.0 
  intl: ^0.17.0
  dio: ^4.0.0
  sizer: ^2.0.13
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^13.0.0
  device_info_plus: ^8.1.0
  flutter_html: ^3.0.0-alpha.3
  image_picker: ^0.8.7+1
  url_launcher: ^6.1.10
  flutter_image_compress: ^1.1.3
  flutter_easyloading: ^3.0.5
  scrollable_positioned_list: ^0.3.5
  sticky_headers: ^0.3.0+2
  timezone: ^0.9.1
  permission_handler: ^10.2.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/utils/
    - assets/image/login/
    - assets/image/profile/
    - assets/image/canteen/
    - .env
